### ISSUE TITLE
unit test: AddMixin(id, location, owner)

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#16]

**Comment by cgourdin** [comment]
Register a user mixin. Please provide me a curl query for that, i have no clue to call this method. 
Thank you

**Comment by jeanparpaillon** [comment]
POST /-/
content-type: text/occi
category: mymixin0; scheme="http://schemas.example.org/occi#"; class=mixin; location="http://localhos:8080/mymixin_collection"

**Comment by philippemerle** [comment]
This issue requires to resolve issue https://github.com/occiware/ecore/issues/64 firstly.

**Comment by philippemerle** [comment]
Commits https://github.com/occiware/ecore/commit/b7edd198c32b53bf07f196bc9a879965c700adf1 added the 'mixins' reference to the Configuration class.
In Java, do configuration.getMixins().add(mixin).
