### ISSUE TITLE
unit test: DelMixin(id)

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#17]

**Comment by cgourdin** [comment]
Like issue #16 , i have no clue for querying this method via Erocci.

**Comment by jeanparpaillon** [comment]
```
DELETE /-/
content-type: text/occi
category: mymixin0; scheme="...."; class=mixin; location=...
```

**Comment by philippemerle** [comment]
This issue requires to resolve issue https://github.com/occiware/ecore/issues/64 firstly.

**Comment by philippemerle** [comment]
Commits https://github.com/occiware/ecore/commit/b7edd198c32b53bf07f196bc9a879965c700adf1 added the 'mixins' reference to the Configuration class.
In Java, do configuration.getMixins().remove(mixin).
