### ISSUE TITLE
Continuous integration with Travis

### ISSUE THREAD

**Issue by philippemerle** [occiware/erocci-dbus-java#19]

**Comment by cgourdin** [comment]
It's done :-)

**Comment by philippemerle** [comment]
Hi Christophe,
You should add the current status of the continuous integration into erocci-dbus-java/doc/devstatus.md.
Take inspiration of https://raw.githubusercontent.com/occiware/ecore/master/README.md and especially the following line:
[![Build Status](https://travis-ci.org/occiware/ecore.svg?branch=master)](https://travis-ci.org/occiware/ecore)
A+
Philippe

**Comment by cgourdin** [comment]
It's done :-)
