### ISSUE TITLE
Add a Progress Daskboard

### ISSUE THREAD

**Issue by philippemerle** [occiware/erocci-dbus-java#20]
This daskboard will list work to do on erocci-dbus-java.
This could be a table with links to Github issues.
In green what is implemented and tested and so useable by backend developers.
In orange what is under development, still bugged, etc.
In red what must be started.

**Comment by cgourdin** [comment]
I have added a progress status page. 
Todo: colored images to symbolize the status tasks

**Comment by philippemerle** [comment]
Hi Christophe,
In https://github.com/occiware/erocci-dbus-java/tree/master/doc, could you remove the 'inria_' prefix to all .png files as this is useless.
A+
Philippe

**Comment by cgourdin** [comment]
It's done.
