### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#23]
Hi,
On every code upgrade (git pull), building erocci-dbus-java is broken
One need to cleanup everything and rebuild from scratch, which takes incredible time, needs downlaoding the whole internet (which prevents from building the project offline).

Can you fix maven build by:
* Integrating all .sh hookd into pom.xml
* ensure dependancies are correctly handled

**Comment by cgourdin** [comment]
As i explain in #24 , i will update this week the maven pom to point directly on a local repo in lib directory as here : http://mark.koli.ch/maven-add-local-jar-dependency-to-classpath
The shell scripts will be removed in next push.

**Comment by jeanparpaillon** [comment]
Thanks !

**Comment by cgourdin** [comment]
Some libraries are on external maven repositories, like "log4j", do you want to build the application without internet connection ?

**Comment by jeanparpaillon** [comment]
Offline build would mean every jar to be on the git repository, so I don't think this is a good idea.
The problem is you need to clean all the build each time some dependancies are upgraded

**Comment by cgourdin** [comment]
As some libraries depends on Clouddesigner that have no external maven repo, for each new cloud designer updated libs, you must :
launch shell script : 
`$> ./dbus-java-install-script.sh 
 $> mvn clean install`
Alternatively : 
`$> make deps`

After that for launching with infrastructure extension only :
`$> mvn exec:java -Dexec.mainClass="org.o.erocci.backend.BackendDBusService"`

For usage with docker schema :
`$> mvn exec:java -Dexec.mainClass="org.o.erocci.backend.BackendDBusService" -Dexec.args="docker"`
