### ISSUE TITLE
When entity conflict, backend should raise org.ow2.erocci.backend.Conflict DBus error

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#32]

**Comment by cgourdin** [comment]
In which case this error is raised in detail ?

**Comment by jeanparpaillon** [comment]
Hum, part of the semantic is up to the backend. In general, conflicts occurs when PUT'ing on an existing entity but the new definition is incompatible with the previous one (occi.core.id is different, for instance).

**Comment by cgourdin** [comment]
ok thanks.

**Comment by cgourdin** [comment]
I made a fix, please check if this is correct.

Thanks.

**Comment by jeanparpaillon** [comment]
Fixed
