### ISSUE TITLE
Mixin attributes assigned to entity but are duplicates of kind attributes

### ISSUE THREAD

**Issue by cgourdin** [occiware/erocci-dbus-java#34]

**Comment by cgourdin** [comment]
This was resolved with commit e82db276f24dda152c1f35b3d5ed348dbc128a04

**Comment by jeanparpaillon** [comment]
fyi, in erocci core each entity maintains a _stack_ of categories defining an attribute, so that mixins can override attribute definitions.

**Comment by cgourdin** [comment]
It's good to know, thanks !
